# Generated by Django 5.1.6 on 2025-07-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="thumbnail",
            field=models.ImageField(default="", upload_to="images/"),
        ),
    ]
